# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # ✅ Vendos env si hap veçmas
      - name: Show GEMINI_API_KEY
        run: echo "GEMINI_API_KEY is set"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # Shembull: Instal dependencies dhe test
      - name: Install dependencies
        run: npm install
        working-directory: server
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Run tests
        run: npm test
        working-directory: server
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
